//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorDeGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorDeGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be
        ///have
        ///it
        ///he
        ///i
        ///they
        ///you
        ///not
        ///she
        ///do
        ///we
        ///will
        ///say
        ///would
        ///can
        ///go
        ///get
        ///make
        ///up
        ///see
        ///other
        ///time
        ///know
        ///take
        ///year
        ///well
        ///like
        ///then
        ///think
        ///come
        ///now
        ///use
        ///over
        ///good
        ///work
        ///give
        ///new
        ///people
        ///look
        ///one
        ///way
        ///right
        ///back
        ///man
        ///find
        ///down
        ///day
        ///need
        ///much
        ///want
        ///last
        ///thing
        ///own
        ///tell
        ///still
        ///must
        ///child
        ///show
        ///mean
        ///put
        ///place
        ///oh
        ///government
        ///become
        ///part
        ///great
        ///change
        ///leave
        ///old
        ///case
        ///life
        ///little
        ///house
        ///system
        ///far
        ///point
        ///long
        ///same
        ///group
        ///end
        ///call
        ///number
        ///woman
        ///feel
        ///seem
        ///might
        ///high
        ///world
        ///area
        ///ask
        ///company
        ///course
        ///home
        ///problem
        ///service
        ///hand
        ///try
        ///form
        ///state
        ///set
        ///school
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lemmas {
            get {
                return ResourceManager.GetString("Lemmas", resourceCulture);
            }
        }
    }
}
